@@ -4,7 +4,7 @@ stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

@@ -14,4 +14,4 @@ install:

build_script:
  - chmod +x gradlew
  - ./gradlew test --info 
  - ./gradlew test --info
